---

- name: Update nodepools, if needed
  command: >
    gcloud container clusters upgrade {{ cluster.name }}
      --node-pool {{ item.name }}
      --cluster-version {{ item.kubeConfig.version | replace("v","")}}
      --project {{ cluster.providerConfig.project }}
      --zone {{ cluster.providerConfig.zone.primaryZone }}
      --no-async
      --quiet
  when: (item.kubeConfig is defined) and (item.kubeConfig.version is defined) and (item.kubeConfig.version != "v0.0.0")
  with_items: "{{ cluster.nodePools }}"
